apiVersion: v2
name: monitoring-umbrella
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 81.3.2
    repository: https://prometheus-community.github.io/helm-charts

  - name: loki
    version: 6.51.0
    repository: https://grafana.github.io/helm-charts

  - name: grafana-operator
    version: v5.18.0
    repository: https://grafana.github.io/helm-charts

  - name: alloy
    version: 1.0.3
    repository: https://grafana.github.io/helm-charts
