apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    name: admin@homelab
  project: default
  source:
    path: manifests/cluster-addons/immich
    repoURL: https://github.com/bakseter/homelab.git
    targetRevision: HEAD
  syncPolicy:
    # TODO: enable
    #   automated:
    #     prune: true
    #     selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
