apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
spec:
  destination:
    namespace: keel
    name: admin@homelab
  project: default
  source:
    path: manifests/cluster-addons/keel
    repoURL: https://github.com/bakseter/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetaData:
      labels:
        pod-security.kubernetes.io/enforce: restricted
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
