apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: five31
  namespace: argocd
spec:
  description: five31 application
  destinations:
    - namespace: five31
      name: admin@homelab
  sourceRepos:
    - https://github.com/bakseter/five31.git
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment

    - group: 'apps'
      kind: ReplicaSet

    - group: ''
      kind: Pod

    - group: ''
      kind: Service

    - group: ''
      kind: ConfigMap

    - group: ''
      kind: Secret

    - group: ''
      kind: ServiceAccount

    - group: ''
      kind: PersistentVolumeClaim

    - group: 'policy'
      kind: PodDisruptionBudget

    - group: 'rbac.authorization.k8s.io'
      kind: Role

    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding

    - group: 'networking.k8s.io'
      kind: NetworkPolicy

    - group: 'cilium.io'
      kind: CiliumNetworkPolicy

    - group: 'networking.k8s.io'
      kind: Ingress

    - group: 'postgresql.cnpg.io'
      kind: Cluster

    - group: 'postgresql.cnpg.io'
      kind: Database

    - group: 'bitnami.com'
      kind: SealedSecret

    - group: 'monitoring.coreos.com'
      kind: ServiceMonitor
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: five31
  namespace: argocd
spec:
  destination:
    namespace: five31
    name: admin@homelab
  project: five31
  source:
    path: manifests
    repoURL: https://github.com/bakseter/five31.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
