apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy-public
  namespace: oauth2-proxy
spec:
  entryPoints:
    - public
  routes:
    - kind: Rule
      match: Host(`auth.bakseter.net`)
      services:
        - name: oauth2-proxy-public
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-private
  namespace: oauth2-proxy
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - backend:
              service:
                name: oauth2-proxy-private
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - auth
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy-private
  namespace: oauth2-proxy
spec:
  entryPoints:
    - private
  routes:
    - kind: Rule
      match: HostRegexp(`^auth\..*\.ts\.net$`)
      services:
        - name: oauth2-proxy-private
          port: 80
