apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers
  namespace: oauth2-proxy
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-public
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy-public.oauth2-proxy.svc.cluster.local/oauth2
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Groups
      - X-Auth-Request-Preferred-Username
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-private
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy-private.oauth2-proxy.svc.cluster.local/oauth2
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Groups
      - X-Auth-Request-Preferred-Username
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: errors-public
  namespace: oauth2-proxy
spec:
  errors:
    status:
      - '401'
      - '403'
    service:
      name: oauth2-proxy-public
      port: 80
    query: '/oauth2/sign_in'
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: errors-private
  namespace: oauth2-proxy
spec:
  errors:
    status:
      - '401'
      - '403'
    service:
      name: oauth2-proxy-private
      port: 80
    query: '/oauth2/sign_in'
