apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCIA2hASPsvqd1sXzYuECq+6/K2WTSxp40CgVzZbMyhYUFWqi9mdweucsDc4SpGyQ0fgM7Eooja00yU8I55ck87cS+6wPZEduW8R3YXIJ4BzJq67WAdyTOtqyfpc6xIhF3A/e4Mm6x6zp1+jzqKAsakz+6/cRiTGVwS8baUL7lU6L0E+DUkQmO0qRhvbZK6OEFLaFIcvfbI7A26B/OCl582PYc9MVYzDXbm59CcpF61JZOsU/OfUA96/HMAIs7dMHA6AMxEzsOgjCFlMGwLaujqAfwgDyTbdWoG/PXwiY1Ya5kydAR09HIq+8r8H5p1UEwiwSzHOXnvJ969JxNc5kcD3iD7pX1b3BUcF0c1B7Y9jXUtbaGvxz+KLQ5W9beIgqJo8B0VuKxF6AHUqbXdRArcmSq4/U5XcNYqXSvNCtNwZ7BSlgSb5oruRv+xlJoFPHj4HCYUd7sY2fTo/z5PGKPuLSUzZv+fhTuVYElmCCgx+JRI6JpQg/9o3LFIej9GUFFoPxk29vX0/o28oyBTTq+azUOb71Jma/hyakZjrrm2OgJW2BmtqzlJFI+ZaIMUFkitwGBoW9TOUhjjT7tBz6T6IXvi2rnvpntTBmWmuP44ctwy1WVfE8kMj+hcz9N+II1T/0LaxcV1pboqei9kT9Dsd+jf+u9CwKIj7C2H2W8I2Fa5UH8alXKumfTY5X5W5sgtY9YxDsAo6INlEm7/fEcYj1Cawjh2vt0EbvsLWXWWX54LwJ8B5jMzWvz1uPGIkX+TLQ8UAuOauJ+Ajza/KH7sFT/aeomT2beMWT7vK7Gsd5qnyAsiBgvkYzWiUvyunqiiD6wAqQZx79xMT8qi9Etx1SHrPgnEvrnJF833BwUB6Yt1C5g2QMT/xNsY6kLqAQgNfCPzz91D/vcczQ80A/L45FshYwQBZc2XPbXfTaowtwTiWiqq4VFH
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
