apiVersion: v2
name: argocd-umbrella
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 9.3.4
    repository: https://argoproj.github.io/argo-helm
  - name: oauth2-proxy
    version: 10.1.0
    repository: https://oauth2-proxy.github.io/manifests
