apiVersion: v2
name: ouath2-proxy-umbrella
version: 0.1.0
dependencies:
  - name: oauth2-proxy-public
    version: 10.1.0
    repository: https://oauth2-proxy.github.io/manifests
  - name: oauth2-proxy-private
    version: 10.1.0
    repository: https://oauth2-proxy.github.io/manifests
