apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secret-key: AgCHxLPvvOYqTIuVlpQJ3hyYvsuWMqWX6K5qQAtWkYZp5n0L09cnKIRRn4imr7916dZycd+hVYVI6ZIRJc9aUUJFKQrdSPMOaC9wuIYcwZHBHfuebqwudwA5GEG24GbI3pTYvboxsDrHIOr+ywXL3C1X6WL1l+/WUB2Lo5ctPJUtfdxTVPabi47Y8tAg2Sdioga+GQ0frRUEb+uvGnL5dDAQgYTVZYt8wyjQxDeaCQZscqpVG5OeVV4VGE7q5djz4TheqX4ATOLOVyshBMlVQ9TzfY77tQAZfwHigj9DcbmPh/sIJVILa4ObhJJgURgWwE+14Mf2xycGoA7i+dq2uj6xeUvyrJuC1mJbRzx8HZ6XDrDEFqh8Fcl3nNh+kS1HGeDxnwUzHknbeMj16GUiSU4I8Cf5v36Gge5Vh/QGmN89GwHHdm8b9g99VP3gC8ayZJBjvQ5AU2bmL45CcPbcp3BuNJQ36u25wed7be972rueLxuCXdluiRM+28c0ZNFTaKHwykjkzZS2eRXGUdb+0eVwvFWb6hGKhtyHXi4RQqrqrx1l6RlqesQrrH05fTWAhs8qMXV3DncMIUPr7JJCldeVXsJWgOEFwMUI5lRR9WzQThFmFOl6FgZjFVc0aMCyvtsinKtzKedDdKf/YbOC+8IOnjGJVVRyjFaLOWhqOD0J0t/Fo1JT6191SPavHIivUKwhDuTvZ5E/r5kWeePT4CKU5mGUawY0ZsgtB9PktPL1QZB4wGIkxiqPOFG+xSUXIwvTj3SHFhCA1LV1XG0qYen6dywTs0Bo8JwOmbkJKo3eAw==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
