apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-tailscale-to-longhorn-ui
  namespace: longhorn-system
spec:
  podSelector:
    matchLabels:
      app: longhorn-ui
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tailscale
          podSelector:
            matchLabels:
              tailscale.com/parent-resource: longhorn-ingress
              tailscale.com/parent-resource-ns: longhorn-system
