apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hetzner-backup
  namespace: longhorn-system
spec:
  cron: '0 3 */3 * *'
  task: backup
  retain: 4
  concurrency: 1
  groups:
    - default
