apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - public
  routes:
    - kind: Rule
      match: Host(`keycloak.bakseter.net`) # && PathRegexp(`^/(realms|resources|\.well-known)/.*`)
      services:
        - name: keycloak-service
          port: http
