apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: traefik
spec:
  encryptedData:
    token: AgCXXV+3v8uqLy72UXZlIv4Fd6Urx+/4O3TzGGFx2pVzLBz42Gbcq1O3MBdeNEv9pWGSj0VIpiCZXf+Ez1gzwScXXcbpmZQQaMCjXUwZ6ALDeAW76X3eSr4oO87xZWP7XcB4d7gOJ3LscgW0tEgGZXeN9WOWEzp28C3BTzOCRlBK6VDVXbTra4Cih3t5kM7jproRW4NqPzEXAAGOehJVGj3cp+rKghM99YAkUefIep7Uue4CqY1iBiHQjojEiFKZrZM2RzaFzurz/tCCzsdhNdg8s6ORjNBLjSluWkjw97yOKJedpZnlbkPJ8PE32qVf6IZRgCr18jzTj9+xmmxtJ5lN0lhINyCWfgwfbeTP1hDbHm8Ri2jOqitjcxiUt0NJ3pdZEbdxTWUJu09RRhle9bTq+J0UCeGAfbrYTpSVuDWb1JpXNOe98b9Ti3wzZ0Oql1mXBMB+mxHkET5RHfLbgLw2m8S5uKKFGHB3foWIXO9DtfSLbEcXKcHE+Xn1YK+z3Cc79DgfAhyoVsResR2f5VW9qwYkFeA92G2+AzSs8YvFLXu3lywIbcKUA5duM58rtUni6X2JEscs0IoN3RtkZw+AmgbcWHHkEAzLIU+hOJCw8LGjuNR1n5hW0Cg8j7EQCzc0lRRAKGQSjxeLBnJqWZSx8lMm5s5WMbVIHfdBwM1G7WaF8fJjty31hqZv24sxJVsQ/KrTGv79yq4zcaZPnbU3al+1XSBg1H9R9HoJkpcEL6hUL0PVGx1kMNmqBMoIDmhF3F432SW2Uq8i4yEGx4n0mqhF22csfnoWcfq5PivygbuoVCytYZWca4YLZx0kKyuOpsQwDkCWg0yXNoJZfMDDHhjaGi18LfamZ0EF47yHyHq2hbUacFzNRGEn1meMgMRb1/BOmVUYXZdaema274IzHfda/nMVZ4pBKD82UgS415Cgcp7huvQW
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: traefik
