keel:
  image:
    # TODO: Replace with upstream when keel fixes their shit
    repository: ghcr.io/bakseter/keel/keel
    tag: latest

  helmProvider:
    enabled: false

  secret:
    enabled: false

  podSecurityContext:
    runAsUser: 666 # matches the UID inside the container
    runAsGroup: 666 # matches the GID inside the container
    fsGroup: 666 # matches the GID inside the container
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
