longhorn:
  preUpgradeChecker:
    jobEnabled: false

  defaultSettings:
    defaultDataPath: /var/lib/longhorn
    createDefaultDiskLabeledNodes: true
    snapshotDataIntegrity: enabled

  defaultBackupStore:
    backupTarget: s3://bakseter-homelab-longhorn@hel1/
    backupTargetCredentialSecret: longhorn-backup-secret
    pollInterval: 600

  persistence:
    defaultClassReplicaCount: 2

  networkPolicies:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: tailscale
    host: longhorn
    tls:
      - hosts:
          - longhorn
